version: '2.1'

services:
  prometheus:
    image: prom/prometheus:v2.32.1
    container_name: prometheus
    volumes:
      - './prometheus/data:/prometheus'
      - './prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=90d'
      - '--storage.tsdb.allow-overlapping-blocks'
    restart: unless-stopped
    ports:
      - '9090:9090'
    expose:
      - 9090

  grafana:
    image: grafana/grafana:8.4.4
    container_name: grafana
    volumes:
      - './grafana/data:/var/lib/grafana'
      - './grafana/provisioning:/etc/grafana/provisioning:ro'
      - './grafana/grafana.ini:/etc/grafana/grafana.ini:ro'
    restart: unless-stopped
    ports:
      - '3000:3000'
    expose:
      - 3000
